/* Header file generated by fdesign on Sun Aug  2 01:50:55 2026 */

#ifndef FD_main_h_
#define FD_main_h_

#include <limits.h>
#include <forms.h>

#define POLLRATE 5.0
#define READRATE 0.5

#define PJL_INFO 1
#define PJL_PARSEERR 2
#define PJL_PARSEWARN 3
#define PJL_SEMERR 4
#define PJL_OPERATOR 5
#define PJL_HWERR 6
#define PJL_UNKNOWN 7

#define BR_RED 1
#define BR_GREEN 2
#define BR_YELLOW 3

extern char prndevice[PATH_MAX];

char* strstat(int);
int intstat(int);
int trafficstat(int);

void br_set_progress_status(FL_OBJECT* obj, int enable);

void onsleep( FL_OBJECT *, long );
void onread( FL_OBJECT *, long );

void onprnfile( FL_OBJECT *, long );

void onprngo( FL_OBJECT *, long );
void onprnmaint( FL_OBJECT *, long );
void onprntest( FL_OBJECT *, long );
void onprnauto( FL_OBJECT *, long );
void ontimer( FL_OBJECT *, long );




/* Forms and Objects */

typedef struct {
    FL_FORM   * main;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * prnfile;
    FL_OBJECT * prngo;
    FL_OBJECT * prninfo;
    FL_OBJECT * prnmaint;
    FL_OBJECT * prntest;
    FL_OBJECT * prnauto;
    FL_OBJECT * timer;
    FL_OBJECT * readtimer;
    FL_OBJECT * tonerbk;
    FL_OBJECT * tonery;
    FL_OBJECT * tonerc;
    FL_OBJECT * tonerm;
	FL_OBJECT * trafficl;

	FL_OBJECT * sleepbtn;
	FL_OBJECT * drum;
	//FL_OBJECT * sleepbtn;
} FD_main;

FD_main * create_form_main( void );
typedef struct {
    FL_FORM   * printing;
    void      * vdata;
    char      * cdata;
    long        ldata;
} FD_printing;

FD_printing * create_form_printing( void );

#endif /* FD_main_h_ */
