/* Form definition file generated by fdesign on Sun Aug  2 01:50:55 2026 */

#include <stdlib.h>
#include <unistd.h>
#include "brinfo.h"

#include "trafficr.xpm"
#include "trafficg.xpm"
#include "trafficy.xpm"

#include "checker.xpm"
#include "checkerhor.xpm"


char prndevice[PATH_MAX];
char prnmodel[128] = "Printer";
char prnstatusstr[256];

char statustext[256+128];

int tries = 0;
int fails = 0;

int drumfull = 0;
int drumleft = 0;
int trafficlight = BR_RED;

void br_activate_button(FL_OBJECT* btn) {
	fl_set_object_lcolor(btn, FL_BLACK);
	fl_activate_object(btn);
}

void br_deactivate_button(FL_OBJECT* btn) {
	fl_set_object_lcolor(btn, FL_INACTIVE);
	fl_deactivate_object(btn);
}


void processbuttons(FL_OBJECT * ob, int status) {
	FD_main* fdui = (FD_main*)ob->form->fdui;

	if (status == 10001 || status == 10006) {
		br_activate_button(fdui->sleepbtn);
	} else {
		br_deactivate_button(fdui->sleepbtn);
	}

	if (trafficlight == BR_RED) {
		br_deactivate_button(fdui->prnmaint);
		br_deactivate_button(fdui->prntest);
	} else {
		br_activate_button(fdui->prnmaint);
		br_activate_button(fdui->prntest);
	}
}

void onread( FL_OBJECT * ob,
         long        data ) {
	FILE *fptr;
	char line[512];

	char keyname[128];
	char keyvalue[128];

	int val;
	int trafficv;

	int drumpercentage;

	FD_main* fdui = (FD_main*)ob->form->fdui;

	//puts("HEllo");

	fptr = fopen(prndevice, "r");

	if (fptr == NULL) {
		if (access(prndevice, F_OK) != 0) {
			fl_set_pixmap_data(fdui->trafficl, trafficr_xpm);
			trafficlight = BR_RED;
			sprintf(statustext, "%s\nOffline", prnmodel);
			fl_set_object_label(fdui->prninfo, statustext);

			processbuttons(ob, 0);
		} else {
			fl_set_pixmap_data(fdui->trafficl, trafficy_xpm);
			trafficlight = BR_YELLOW;
			sprintf(statustext, "%s\nIn use", prnmodel);
			fl_set_object_label(fdui->prninfo, statustext);

			processbuttons(ob, 0);
		}

		fl_set_timer(fdui->readtimer, READRATE);

		fails = 0;		
		return;
	}

	fails = 0;

	while (fgets(line, sizeof(line), fptr)) {
		//fputs(line, stdout);
		if (sscanf(line, "%127[^=]=\"%127[^\"]\"", keyname, keyvalue) == 2 ||
				sscanf(line, "%127[^=]=%127s", keyname, keyvalue) == 2) {
			if (strcmp("CODE", keyname) == 0) {
				sprintf(statustext, "%s\n%s", prnmodel, strstat(atoi(keyvalue)));
				fl_set_object_label(fdui->prninfo, statustext);

				trafficv = trafficstat(atoi(keyvalue));
				
				if (trafficv == BR_RED) {
					fl_set_pixmap_data(fdui->trafficl, trafficr_xpm);
					trafficlight = BR_RED;
				} else if (trafficv == BR_GREEN) {
					fl_set_pixmap_data(fdui->trafficl, trafficg_xpm);
					trafficlight = BR_GREEN;
				} else if (trafficv == BR_YELLOW) {
					fl_set_pixmap_data(fdui->trafficl, trafficy_xpm);
					trafficlight = BR_YELLOW;
				}

				processbuttons(ob, atoi(keyvalue));
			} else if (strcmp("LAS_TONER_REMAIN", keyname) == 0) {
				br_set_progress_status(fdui->tonerbk, 1);
				fl_set_slider_value(fdui->tonerbk, atoi(keyvalue));
				br_set_progress_status(fdui->tonery, 0);
				br_set_progress_status(fdui->tonerc, 0);
				br_set_progress_status(fdui->tonerm, 0);
			} else if (strcmp("LAS_KTONER_REMAIN", keyname) == 0) {
				br_set_progress_status(fdui->tonerbk, 1);
				fl_set_slider_value(fdui->tonerbk, atoi(keyvalue));
				br_set_progress_status(fdui->tonery, 1);
				br_set_progress_status(fdui->tonerc, 1);
				br_set_progress_status(fdui->tonerm, 1);
			} else if (strcmp("LAS_CTONER_REMAIN", keyname) == 0) {
				fl_set_slider_value(fdui->tonerc, atoi(keyvalue));
			} else if (strcmp("LAS_MTONER_REMAIN", keyname) == 0) {
				fl_set_slider_value(fdui->tonerm, atoi(keyvalue));
			} else if (strcmp("LAS_YTONER_REMAIN", keyname) == 0) {
				fl_set_slider_value(fdui->tonery, atoi(keyvalue));
			} else if (strcmp("LAS_MODEL_NAME", keyname) == 0) {
				strcpy(prnmodel, keyvalue);
			} else if (strcmp("LAS_DRUM_LIFE_PERIOD", keyname) == 0) {
				drumfull = atoi(keyvalue);
			} else if (strcmp("LAS_NEXTCARE_DRUM", keyname) == 0) {
				drumleft = atoi(keyvalue);
				if (drumfull != 0) {
					drumpercentage = drumleft * 100 / drumfull;

					br_set_progress_status(fdui->drum, 1);
					fl_set_slider_value(fdui->drum, drumpercentage);
				}
			}

		}
	}

	fclose(fptr);
	fl_set_timer(fdui->readtimer, READRATE);
}


void onprnfile( FL_OBJECT * ob,
         long        data )
{
}

void onprngo( FL_OBJECT * ob,
         long        data )
{
	FILE* fp;
	
	FD_main* fdui = (FD_main*)ob->form->fdui;

	if (fl_get_button(fdui->prnauto)) {
		fl_set_timer(fdui->timer, POLLRATE);
	}

	if (ob == fdui->prngo) {
		strcpy(prndevice, fl_get_input(fdui->prnfile));
		strcpy(prnmodel, "Printer");

		tries = 0;
	}

	if (access(prndevice, F_OK) != 0) {
		fl_set_pixmap_data(fdui->trafficl, trafficr_xpm);
		trafficlight = BR_RED;
		sprintf(statustext, "%s\nOffline", prnmodel);
		fl_set_object_label(fdui->prninfo, statustext);

		br_set_progress_status(fdui->drum, 0);
		br_set_progress_status(fdui->tonerbk, 0);
		br_set_progress_status(fdui->tonery, 0);
		br_set_progress_status(fdui->tonerc, 0);
		br_set_progress_status(fdui->tonerm, 0);

		processbuttons(ob, 0);

		return;
	}

	fp = fopen(prndevice, "w");

	if (fp == NULL) {
		fl_set_pixmap_data(fdui->trafficl, trafficy_xpm);
		trafficlight = BR_YELLOW;
		sprintf(statustext, "%s\nIn use", prnmodel);
		fl_set_object_label(fdui->prninfo, statustext);

		processbuttons(ob, 0);

		return;
	}

	if (tries == 0) {
		fprintf(fp, "\033%%-12345X@PJL INFO BRSUPPLY\n\033%%-12345X");
	}
	
	fprintf(fp, "\033%%-12345X@PJL INFO STATUS\n\033%%-12345X");
	fclose(fp);

	if (++tries == 15) tries = 0;
}


void onprnmaint( FL_OBJECT * ob,
         long        data )
{
	FILE* fp;
	fp = fopen(prndevice, "w");

	if (fp == NULL) return;
	fprintf(fp, "\033%%-12345X@PJL EXECUTE MAINTENANCEPRINT\n\033%%-12345X");
	fclose(fp);
}

void onprntest( FL_OBJECT * ob,
         long        data )
{
	FILE* fp;

	fp = fopen(prndevice, "w");

	if (fp == NULL) return;
	fprintf(fp, "\033%%-12345X@PJL EXECUTE TESTPRINT\n\033%%-12345X");
	fclose(fp);
}

void onsleep( FL_OBJECT * ob,
         long        data )
{
	FILE* fp;

	fp = fopen(prndevice, "w");

	if (fp == NULL) return;
	fprintf(fp, "\033%%-12345X@PJL EXECUTE SHUTDOWN\n\033%%-12345X");
	fclose(fp);
}

void onprnauto(FL_OBJECT* ob, long data) {
	FD_main* fdui = (FD_main*)ob->form->fdui;

	if (fl_get_button(ob)) {
		fl_set_timer(fdui->timer, POLLRATE);
	} else {
		fl_set_timer(fdui->timer, 0.0);
	}
}


FL_OBJECT* br_add_button(FL_Coord x, FL_Coord y, FL_Coord w, FL_Coord h,
		const char* label) {
	FL_OBJECT* obj;

	obj = fl_add_button(FL_NORMAL_BUTTON, x, y, w, h, label);
	fl_set_object_lalign(obj, FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
	fl_set_button_mouse_buttons(obj, 1);

	return obj;
}

void br_set_progress_status(FL_OBJECT* obj, int enable) {
	if (obj->u_vdata != NULL) {
		if (enable) {
			fl_hide_object(obj->u_vdata);
		} else {
			fl_show_object(obj->u_vdata);
			fl_set_slider_value(obj, 100);
		}
	} else {
		if (!enable) {
			fl_set_slider_value(obj, 0);
		}
	}
}

FL_OBJECT* br_add_vertical_progress(FL_Coord x, FL_Coord y, const char* label, FL_COLOR col) {
	FL_OBJECT* obj;
	FL_OBJECT* obj2;
	
	obj = fl_add_slider(FL_VERT_PROGRESS_BAR, x, y, 20, 90, label);
    fl_set_object_color(obj, FL_COL1, col);
    fl_set_slider_bounds(obj, 100, 0);
    fl_set_slider_value(obj, 100);
	fl_set_object_bw(obj, 1);

    obj2 = fl_add_pixmap(FL_NORMAL_PIXMAP, x, y, 20, 90, "");
    fl_set_pixmap_data(obj2, checker_xpm);
	fl_set_object_bw(obj2, 1);
	fl_hide_object(obj2);
	obj->u_vdata = obj2;

	return obj;
}


FL_OBJECT* br_add_horizontal_progress(FL_Coord x, FL_Coord y, const char* label, FL_COLOR col) {
	FL_OBJECT* obj;
	FL_OBJECT* obj2;
	
	obj = fl_add_slider(FL_HOR_PROGRESS_BAR, x, y, 110, 20, label);
    fl_set_object_color(obj, FL_COL1, col);
    fl_set_slider_bounds(obj, 0, 100);
    fl_set_slider_value(obj, 100);
	fl_set_object_bw(obj, 1);

    obj2 = fl_add_pixmap(FL_NORMAL_PIXMAP, x, y, 110, 20, "");
    fl_set_pixmap_data(obj2, checkerhor_xpm);
	fl_set_object_bw(obj2, 1);
	//fl_hide_object(obj2);
	obj->u_vdata = obj2;

	return obj;
}

FD_main *
create_form_main( void )
{
    FL_OBJECT *obj;
    FD_main *fdui = ( FD_main * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->main = fl_bgn_form( FL_NO_BOX, 304, 227 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 304, 227, "" );
    fl_set_object_resize( obj, FL_RESIZE_NONE );


    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 60, 20, "Device:" );
    fl_set_button_shortcut( obj, "#M", 1 );

	fdui->prnfile = obj = fl_add_input( FL_NORMAL_INPUT, 70, 10, 105, 20, "" );
    fl_set_object_callback( obj, onprnfile, 0 );
	fl_set_input(obj, "/dev/usb/lp1");
	fl_set_input_maxchars(obj, PATH_MAX-1);
	strcpy(prndevice, fl_get_input(obj));
	
    fdui->prngo = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 10, 60, 20, "Connect" );
    fl_set_object_callback( obj, onprngo, 0 );
    fl_set_button_shortcut( obj, "\r", 1 );
	fl_set_button_mouse_buttons(obj, 1);


    fdui->prnauto = obj = fl_add_lightbutton( FL_PUSH_BUTTON, 240, 10, 50, 20, "Auto" );
    fl_set_button_shortcut( obj, "#A", 1 );
    fl_set_object_callback( obj, onprnauto, 0 );
    fl_set_button( obj, 1 );


	obj = fl_add_box( FL_DOWN_BOX, 4, 40, 297, 3, "" );
	fl_set_object_bw(obj, 1);

	fdui->prninfo = fl_add_text( FL_NORMAL_TEXT, 50, 50, 245, 40, "Printer\nOffline" );

    fdui->trafficl = obj = fl_add_pixmap( FL_NORMAL_PIXMAP, 10, 50, 40, 40, "" );
    fl_set_pixmap_data( obj, trafficr_xpm );

	obj = fl_add_box(FL_DOWN_BOX, 4, 96, 297, 3, "");
	fl_set_object_bw(obj, 1);

    fdui->prnmaint = obj = br_add_button(10, 110, 160, 20, "Send Maintenance Print" );
    fl_set_button_shortcut( obj, "#M", 1 );
    fl_set_object_callback( obj, onprnmaint, 0 );
	br_deactivate_button(obj);

    fdui->prntest = obj = br_add_button(10, 135, 160, 20, "Send Test Print" );
    fl_set_button_shortcut( obj, "#T", 1 );
    fl_set_object_callback( obj, onprntest, 0 );
	br_deactivate_button(obj);

    fdui->drum = obj = br_add_horizontal_progress(60, 190, "", FL_BOTTOM_BCOL);

	obj = fl_add_text( FL_NORMAL_TEXT, 10, 190, 50, 20, "Drum:" );

	obj = br_add_button(95, 160, 75, 20, "Configure..." );
    fl_set_button_shortcut( obj, "#C", 1 );
    //fl_set_object_callback( obj, onprntest, 0 );
	fl_set_object_lcolor(obj, FL_INACTIVE);
	fl_deactivate_object(obj);
		
	fdui->sleepbtn = obj = br_add_button(10, 160, 80, 20, "Enter Sleep" );
    fl_set_button_shortcut( obj, "#S", 1 );
    fl_set_object_callback( obj, onsleep, 0 );

	fdui->tonerbk = br_add_vertical_progress(180, 110, "BK", FL_BLACK);
	br_set_progress_status(fdui->tonerbk, 0);
	fdui->tonery = br_add_vertical_progress(210, 110, "Y", FL_YELLOW);
	br_set_progress_status(fdui->tonery, 0);
	fdui->tonerc = br_add_vertical_progress(240, 110, "C", FL_CYAN);
	br_set_progress_status(fdui->tonerc, 0);
	fdui->tonerm = br_add_vertical_progress(270, 110, "M", FL_MAGENTA);
	br_set_progress_status(fdui->tonerm, 0);


	// TIMER
    fdui->timer = obj = fl_add_timer( FL_HIDDEN_TIMER, 0,0,0,0, "");
	fl_set_timer(fdui->timer, 0.1);
	fl_set_object_callback(fdui->timer, onprngo, 0);

    fdui->readtimer = obj = fl_add_timer( FL_HIDDEN_TIMER, 0,0,0,0, "");
	fl_set_object_callback(fdui->readtimer, onread, 0);
	fl_set_timer(fdui->readtimer, READRATE);
	
	fl_set_object_lcolor(fdui->sleepbtn, FL_INACTIVE);
	fl_deactivate_object(fdui->sleepbtn);

    fl_end_form();

    fdui->main->fdui = fdui;

	//puts(strstat(10001));

    return fdui;
}


int main(int argc, char* argv[]) {
	FD_main *fd_main;
	//fl_set_icm_color(FL_COL1, 192, 192, 192);
	fl_set_border_width(2);
	fl_initialize(&argc, argv, 0, 0, 0);
	fd_main = create_form_main();

	fl_show_form(fd_main->main, FL_PLACE_CENTER, FL_FULLBORDER, "brinfo");

	fl_do_forms();

	if (fl_form_is_visible(fd_main->main)) fl_hide_form(fd_main->main);
	fl_free(fd_main);
	
	fl_finish();

	return 0;
}
